package.path = "./usr/lib/lua/?.lua;./tests/?.lua;" .. package.path
local H = require("pt_harness")
after_each(function() H.finish() end)
local function begin(body)
    H.begin({ popen = function() return body .. "\nPT_CURL_EXIT:0\n" end })
    return require("podkop-tweaker.api_diag")
end
describe("external DNS observation", function()
    it("creates six fixed-provider probe hosts, no router DNS probe", function()
        local api = begin("12345\n")
        local result = api.dns_observation_start()
        assert.is_true(result.success)
        assert.equal("current_browser", result.scope)
        assert.equal(6, #result.hosts)
        assert.equal("1.12345.bash.ws", result.hosts[1])
        assert.equal("6.12345.bash.ws", result.hosts[6])
        for _, cmd in ipairs(H.popen_cmds()) do assert.falsy(cmd:find("nslookup", 1, true)); assert.falsy(cmd:find("ping ", 1, true)) end
    end)
    it("rejects malformed provider IDs and client IDs before using them in an URL", function()
        for _, id in ipairs({ "../evil", "id?redirect=evil", "id\nheader", "id.", "-id", "id-", string.rep("a", 64) }) do
            local api = begin(id)
            assert.truthy(api.dns_observation_start().error)
            local before = #H.popen_cmds()
            assert.truthy(api.dns_observation_results(id).error)
            assert.equal(before, #H.popen_cmds())
            H.finish()
        end
    end)
    it("returns typed resolver/control facts, drops duplicates and ignores generic VPN conclusions", function()
        local api = begin('[{"type":"ip","ip":"203.0.113.10","country_name":"X","asn":"AS1"},' ..
            '{"type":"dns","ip":"1.1.1.1","country_name":"Y","asn":"AS13335"},' ..
            '{"type":"dns","ip":"1.1.1.1"},{"type":"dns","ip":"2001:db8::1"},' ..
            '{"type":"dns","ip":"<script>bad</script>"},{"type":"conclusion","ip":"No leak"}]')
        local result = api.dns_observation_results("12345")
        assert.is_true(result.complete)
        assert.equal(2, #result.resolvers)
        assert.equal("AS13335", result.resolvers[1].asn)
        assert.equal("router", result.control_request_scope)
        assert.equal("203.0.113.10", result.control_request_ips[1].ip)
        assert.is_nil(result.leak_detected)
        assert.falsy(result.conclusion:find("No leak", 1, true))
    end)
    it("no DNS observations is inconclusive, never no-leak success", function()
        local result = begin('[]').dns_observation_results("12345")
        assert.is_false(result.complete)
        assert.same({}, result.resolvers)
        assert.matches("no conclusion", result.conclusion)
    end)
    it("bounds the provider response and rejects malformed JSON", function()
        assert.truthy(begin("not JSON").dns_observation_results("12345").error)
        H.finish()
        assert.truthy(begin(string.rep("x", 66000)).dns_observation_results("12345").error)
    end)
end)
