package.path = "./usr/lib/lua/?.lua;./tests/?.lua;" .. package.path
local H = require("pt_harness")
after_each(function() H.finish() end)

describe("checked file operations", function()
    for _, operation in ipairs({ "open", "write", "close" }) do
        local fail = operation
        it("keeps the original on temporary " .. fail .. " failure", function()
            H.begin({ failures = { ["/config.tmp-write"] = { [fail] = true, partial = 2 } } })
            H.vfs_write("/config", "old")
            local ok = require("podkop-tweaker.services").write_file_atomic("/config", "new config")
            assert.is_false(ok)
            assert.equal("old", H.vfs_read("/config"))
            assert.falsy(H.vfs_exists("/config.tmp-write"))
        end)
    end
    it("cleans up a failed rename without truncating the target", function()
        H.begin({ failures = { ["/config"] = { rename = true } } })
        H.vfs_write("/config", "old")
        assert.is_false(require("podkop-tweaker.services").write_file_atomic("/config", "new"))
        assert.equal("old", H.vfs_read("/config"))
        assert.falsy(H.vfs_exists("/config.tmp-write"))
    end)
    it("does not replace an executable when chmod fails", function()
        H.begin({ execute = { { match = "chmod", out = 1 } } })
        H.vfs_write("/script", "old script")
        assert.is_false(require("podkop-tweaker.services").write_file_atomic("/script", "new script", { executable = true }))
        assert.equal("old script", H.vfs_read("/script"))
    end)
    it("distinguishes a missing optional backup source from an unreadable existing source", function()
        H.begin({ failures = { ["/private"] = { open = true } } })
        local srv = require("podkop-tweaker.services")
        assert.is_true(srv.backup_to("/missing", "/backup"))
        assert.is_false(srv.backup_to("/missing", "/backup", true))
        assert.is_false(srv.backup_to("/private", "/backup"))
    end)
    it("failed backup flush preserves the previous backup", function()
        H.begin({ failures = { ["/backup.tmp"] = { close = true } } })
        H.vfs_write("/config", "current")
        H.vfs_write("/backup", "last good")
        assert.is_false(require("podkop-tweaker.services").backup_to("/config", "/backup"))
        assert.equal("last good", H.vfs_read("/backup"))
    end)
    it("rollback remains atomic when writing fails", function()
        H.begin({ failures = { ["/config.tmp-write"] = { write = true } } })
        H.vfs_write("/config", "current")
        H.vfs_write("/backup", "last good")
        assert.is_false(require("podkop-tweaker.services").restore_backup({ config = "/config", backup = "/backup" }))
        assert.equal("current", H.vfs_read("/config"))
    end)
end)
