package.path = "./usr/lib/lua/?.lua;./tests/?.lua;" .. package.path
local H = require("pt_harness")
local CFG, BACKUP = "/etc/config/podkop", "/etc/config/podkop.sub-backup"
local BASE = "config section 'main'\n option connection_type 'proxy'\n option proxy_config_type 'url'\n option proxy_string 'vless://old@host:443#old'\n"
after_each(function() H.finish() end)
describe("untrusted subscription bytes and logical UCI replacement", function()
    it("rejects NUL and control bytes before any config/backup write", function()
        H.begin({})
        H.vfs_write(CFG, BASE)
        H.vfs_write(BACKUP, "last good")
        local s = require("pt-subs-lib")
        for _, byte in ipairs({ "\0", "\1", "\t", "\r", "\n", "\127" }) do
            assert.is_false(s.replace_proxy_link("main", "url", 0, "vless://new@host:443#bad" .. byte, BACKUP))
        end
        assert.equal(BASE, H.vfs_read(CFG))
        assert.equal("last good", H.vfs_read(BACKUP))
        for _, call in ipairs(H.state().io_log) do
            assert.falsy(call.operation == "open" and (call.path == CFG or call.path == BACKUP), "invalid links must be rejected before opening configuration")
        end
    end)
    it("rejects raw and outer-base64 NUL and too many/oversized proxy links", function()
        H.begin({})
        local s = require("pt-subs-lib")
        local links, err = s.parse_subscription_raw("vless://a@host:443#bad\0tail")
        assert.equal(0, #links); assert.matches("control", err)
        links, err = s.parse_subscription_raw("dmxlc3M6Ly9hQGhvc3Q6NDQzI2JhZAB0YWls")
        assert.equal(0, #links); assert.matches("control", err)
        links, err = s.parse_subscription_raw("vless://a@host:443#" .. string.rep("n", s.LINK_MAX_SIZE))
        assert.equal(0, #links); assert.matches("oversized", err)
        links, err = s.parse_subscription_raw(string.rep("vless://a@host:443#n\n", s.SUB_MAX_PROXIES + 1))
        assert.equal(0, #links); assert.matches("Too many", err)
    end)
    it("preserves quotes, backslashes, percent literals and unrelated multiline values", function()
        H.begin({})
        local cfg = BASE .. " option user_domains_text 'first\nconfig section ghost\noption proxy_string fake\nlast'\n"
        H.vfs_write(CFG, cfg)
        local link = "vless://new@host:443#O'Reilly%25\\literal"
        assert.is_true(require("pt-subs-lib").replace_proxy_link("main", "url", 0, link, BACKUP))
        local result = H.vfs_read(CFG)
        assert.truthy(result:find("O'\\''Reilly%25\\literal", 1, true))
        assert.truthy(result:find("user_domains_text 'first\nconfig section ghost\noption proxy_string fake\nlast'", 1, true))
        assert.equal(cfg, H.vfs_read(BACKUP))
    end)
    it("replaces complete multiline option/list targets and preserves CRLF and comments", function()
        H.begin({})
        local s = require("pt-subs-lib")
        local cfg = "config section 'main'\r\n option proxy_string 'vless://a@host:443#first\r\nsecond' # keep\r\n"
        H.vfs_write(CFG, cfg)
        assert.is_true(s.replace_proxy_link("main", "url", 0, "vless://new@host:443#new"))
        assert.equal("config section 'main'\r\n option proxy_string 'vless://new@host:443#new' # keep\r\n", H.vfs_read(CFG))
        H.vfs_write(CFG, "config section 'main'\n list selector_proxy_links 'vless://a@host:443#first\nsecond'\n list selector_proxy_links 'vless://b@host:443#b'\n")
        assert.is_true(s.replace_proxy_link("main", "selector", 1, "vless://new@host:443#new"))
        assert.truthy(H.vfs_read(CFG):find("#first\nsecond'", 1, true))
        assert.truthy(H.vfs_read(CFG):find("selector_proxy_links 'vless://new@host:443#new'", 1, true))
    end)
    it("does not overwrite a last-good backup when candidate validation or backup flush fails", function()
        H.begin({ failures = { [BACKUP .. ".tmp"] = { close = true } } })
        H.vfs_write(CFG, BASE)
        H.vfs_write(BACKUP, "last good")
        local s = require("pt-subs-lib")
        assert.is_false(s.replace_proxy_link("main", "url", 0, "vless://new@host:443#new", BACKUP))
        assert.equal(BASE, H.vfs_read(CFG))
        assert.equal("last good", H.vfs_read(BACKUP))
        H.vfs_write(CFG, BASE .. " option bad 'unclosed\n")
        assert.is_false(s.replace_proxy_link("main", "url", 0, "vless://new@host:443#new", BACKUP))
        assert.equal("last good", H.vfs_read(BACKUP))
    end)
    it("auto-update rejects a malicious response without backup/write/restart", function()
        H.begin({ uci = { podkop = { H.sec("main", "section", { connection_type = "proxy", proxy_config_type = "url", proxy_string = "vless://old@host:443#old" }) } },
            popen = function() return "vless://new@host:443#new\0tail\nPT_CURL_EXIT:0\n" end })
        H.vfs_write(CFG, BASE)
        H.vfs_write("/subs.json", '{"main":[{"subscription_url":"https://provider.test","proxy_name":"old"}]}')
        local r = require("pt-subs-lib").update_all_subscriptions("/subs.json", "/log", 25, "auto")
        assert.equal(0, r.updated); assert.equal(1, r.failed); assert.is_false(r.need_restart)
        assert.equal(BASE, H.vfs_read(CFG))
        assert.falsy(H.vfs_exists(BACKUP))
    end)
end)
